from typing import Literal

from .base import OpenAIBaseModel


class OpenAIEmbedding(OpenAIBaseModel):
    embedding: list[float]
    """The embedding vector, which is a list of floats.

    The length of vector depends on the model as listed in the
    [embedding guide](https://platform.openai.com/docs/guides/embeddings).
    """

    index: int
    """The index of the embedding in the list of embeddings."""

    object: Literal["embedding"]
    """The object type, which is always "embedding"."""


class OpenAIUsage(OpenAIBaseModel):
    prompt_tokens: int
    """The number of tokens used by the prompt."""

    total_tokens: int
    """The total number of tokens used by the request."""


class OpenAIEmbeddingResponse(OpenAIBaseModel):
    data: list[OpenAIEmbedding]
    """The list of embeddings generated by the model."""

    model: str
    """The name of the model used to generate the embedding."""

    object: Literal["list"]
    """The object type, which is always "list"."""

    usage: OpenAIUsage
    """The usage information for the request."""
